using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace XP2AFSAirportConverter.Models
{
    public class TSCFile
    {
        public string ICAO { get; set; }

        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();

            sb.AppendLine("<[file][][]");
            sb.AppendLine("<[tmsimulator_scenery_place][][]");
            sb.AppendLine("");
            sb.AppendLine("//////////////////////////////////////////////////////////////////////////////");
            sb.AppendLine("// Generated by XP2AFSAirportConverter");
            sb.AppendLine("//////////////////////////////////////////////////////////////////////////////");
            sb.AppendLine("");
            sb.AppendLine("//////////////////////////////////////////////////////////////////////////////");
            sb.AppendLine("// general information");
            sb.AppendLine("//////////////////////////////////////////////////////////////////////////////");
            sb.AppendLine("<[string8]   [type]          [airport]>");
            sb.AppendLine("<[string8]   [sname]         [Kingman_Airport]>");
            sb.AppendLine("<[string8]   [lname]         [Kingman_Airport]>");
            sb.AppendLine("<[string8]   [icao]          [" + this.ICAO + "]>");
            sb.AppendLine("<[tmvector2d][position]      [-113.93607930 35.25169131]>");
            sb.AppendLine("<[float64]   [height]        [1023.00000000]>");
            sb.AppendLine("<[float64]   [size]          [5000]>");
            sb.AppendLine("<[tmvector2d][tower_position][-113.944478476308 35.2587362691909]>");
            sb.AppendLine("<[float64]   [tower_height]  [18.23736382]>");
            sb.AppendLine("<[bool]      [autoheight]    [true]>");
            sb.AppendLine("<[string8]   [coordinate_system][lonlat]>");
            sb.AppendLine("");
            sb.AppendLine("");
            sb.AppendLine("//////////////////////////////////////////////////////////////////////////////");
            sb.AppendLine("// objects");
            sb.AppendLine("//////////////////////////////////////////////////////////////////////////////");
            sb.AppendLine("<[tmsimulator_scenery_objecttmslist][objects][]");
            sb.AppendLine("  <[tmsimulator_scenery_object][element][0]");
            sb.AppendLine("    <[string8][type][ground]>");
            sb.AppendLine("    <[string8][geometry][kigm_kingman_rwy]>");
            sb.AppendLine("    <[tmvector3d][position][-113.96251900 35.25751700 0]>");
            sb.AppendLine("  >");
            sb.AppendLine("  <[tmsimulator_scenery_object][element][1]");
            sb.AppendLine("    <[string8][type][decal]>");
            sb.AppendLine("    <[string8][geometry][kigm_kingman_decal]>");
            sb.AppendLine("    <[tmvector3d][position][-113.96251900 35.25751700 0]>");
            sb.AppendLine("  >");
            sb.AppendLine("  <[tmsimulator_scenery_object][element][2]");
            sb.AppendLine("    <[string8][type][object]>");
            sb.AppendLine("    <[string8][geometry][kigm_kingman_obj]>");
            sb.AppendLine("    <[tmvector3d][position][-113.96251900 35.25751700 0]>");
            sb.AppendLine("  >");
            sb.AppendLine("  <[tmsimulator_scenery_object][element][3]");
            sb.AppendLine("    <[string8][type][object_transparent_atc]>");
            sb.AppendLine("    <[string8][geometry][kigm_kingman_atc]>");
            sb.AppendLine("    <[tmvector3d][position][-113.96251900 35.25751700 0]>");
            sb.AppendLine("  >");
            sb.AppendLine(">");
            sb.AppendLine("");
            sb.AppendLine("");
            sb.AppendLine("//////////////////////////////////////////////////////////////////////////////");
            sb.AppendLine("// runways");
            sb.AppendLine("//////////////////////////////////////////////////////////////////////////////");
            sb.AppendLine("<[tmsimulator_runwaytmslist][runways][]");
            sb.AppendLine("  <[tmsimulator_runway][element][0]");
            sb.AppendLine("    <[string8][name1][35]>");
            sb.AppendLine("    <[tmvector2d][threshold1][-113.936079297288 35.2516913147237]>");
            sb.AppendLine("    <[tmvector2d][endpoint1][-113.936079297288 35.2516251282721]>");
            sb.AppendLine("    <[string8]   [appltsys1][std]>");
            sb.AppendLine("    <[string8]   [papi1][left]>");
            sb.AppendLine("    <[string8]   [reil1][none]>");
            sb.AppendLine("    <[string8][name2][17]>");
            sb.AppendLine("    <[tmvector2d][threshold2][-113.936079291917 35.2700753770068]>");
            sb.AppendLine("    <[tmvector2d][endpoint2][-113.936079291917 35.2701271153089]>");
            sb.AppendLine("    <[string8]   [appltsys2][std]>");
            sb.AppendLine("    <[string8]   [papi2][left]>");
            sb.AppendLine("    <[string8]   [reil2][none]>");
            sb.AppendLine("    <[float64][width][21.00]>");
            sb.AppendLine("  >");
            sb.AppendLine("  <[tmsimulator_runway][element][1]");
            sb.AppendLine("    <[string8][name1][03]>");
            sb.AppendLine("    <[tmvector2d][threshold1][-113.948145221728 35.2515107787753]>");
            sb.AppendLine("    <[tmvector2d][endpoint1][-113.948675532414 35.2510757094387]>");
            sb.AppendLine("    <[string8]   [appltsys1][std]>");
            sb.AppendLine("    <[string8]   [papi1][left]>");
            sb.AppendLine("    <[string8]   [reil1][none]>");
            sb.AppendLine("    <[string8][name2][21]>");
            sb.AppendLine("    <[tmvector2d][threshold2][-113.931978991298 35.2647724243456]>");
            sb.AppendLine("    <[tmvector2d][endpoint2][-113.931468955901 35.2651907877746]>");
            sb.AppendLine("    <[string8]   [appltsys2][std]>");
            sb.AppendLine("    <[string8]   [papi2][left]>");
            sb.AppendLine("    <[string8]   [reil2][none]>");
            sb.AppendLine("    <[float64][width][46.00]>");
            sb.AppendLine("  >");
            sb.AppendLine(">");
            sb.AppendLine("");
            sb.AppendLine("");
            sb.AppendLine("//////////////////////////////////////////////////////////////////////////////");
            sb.AppendLine("// parking positions");
            sb.AppendLine("//////////////////////////////////////////////////////////////////////////////");
            sb.AppendLine("<[tmsimulator_parking_positiontmslist][parking_positions][]");
            sb.AppendLine("  <[tmsimulator_parking_position][element][0]");
            sb.AppendLine("    <[tmvector2d][position][-113.941247019787 35.2605157165704]>");
            sb.AppendLine("    <[float64][heading][224.40]>");
            sb.AppendLine("    <[string8][name][Parking Position #1]>");
            sb.AppendLine("  >");
            sb.AppendLine(">");
            sb.AppendLine("");
            sb.AppendLine("");
            sb.AppendLine(">");
            sb.AppendLine(">");
            sb.AppendLine("");
            sb.AppendLine("");

            return sb.ToString();

        }
    }
}
